export const STORAGE_IDENTITY_KEY = 'identity'
export const CACHE_TXS_KEY = 'cached_txs'
export const CACHE_BACKUP_KEY = 'backup'
export const CACHE_CLAIM_VOUCHER = 'voucher_claimed'
export const LAWALLET_VERSION = 'v1.0.0'
